// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2018 Vlad & Serge Strukoff. All Rights Reserved.
(function(){function u(){var b=f("pass"),c=E.call(a,f("length").value),d=new Uint32Array(25);w.call(x,d);for(var g=0;g<d.length;g++)e+=F.call(d[g],36);var e=G.call(e,-c);d=new Uint8Array(1);var h="";for(g=0;g<e.length;g++)c=e.charAt(g),H(c)&&(w.call(x,d),128<d[0]&&(c=I.call(c))),h+=c;b.value=h;b.select()}function J(){var a=f("pass");a&&(K.call(y,L.call(z,{id:50,v:a.value})),a.focus())}function f(a){return M.call(N,a)}var a=self.window,N=a.document,z=a.JSON,x=a.crypto,h=a.Object,d=a.chrome,y=d.runtime;
chrome_windows=d.windows;chrome_i18n=d.i18n;var K=y.sendMessage,O=chrome_windows.getCurrent,P=chrome_windows.update,Q=chrome_i18n.getMessage,A=String.prototype,B=Navigator.prototype,R=XMLHttpRequest.prototype,C=DocumentFragment.prototype,b=Document.prototype,D=DOMImplementation.prototype,k=EventTarget.prototype,p=Event.prototype,e=Node.prototype,c=Element.prototype,l=HTMLElement.prototype,q=k.addEventListener,M=b.getElementById,w=Crypto.prototype.getRandomValues,F=Number.prototype.toString,G=A.slice,
I=A.toUpperCase,L=z.stringify,E=a.parseInt,H=a.isNaN;try{var m=h.getOwnPropertyDescriptor(Function.prototype,"call");m&&(m.configurable=!1,m.writable=!1,h.defineProperty(Function.prototype,"call",m))}catch(v){}var n=h.getOwnPropertyDescriptor(e,"textContent");try{C.querySelector=C.querySelectorAll=b.adoptNode=b.append=b.captureEvents=b.getElementById=b.getElementsByClassName=b.getElementsByName=b.getElementsByTagName=b.getElementsByTagNameNS=b.createDocumentFragment=b.createTextNode=b.createElement=
b.createElementNS=b.evaluate=b.createEvent=b.createCDATASection=b.execCommand=b.querySelector=b.querySelectorAll=b.open=b.write=b.writeln=b.prepend=b.importNode=b.registerElement=D.createHTMLDocument=D.createDocument=k.addEventListener=k.removeEventListener=k.dispatchEvent=p.preventDefault=p.stopPropagation=p.stopImmediatePropagation=e.appendChild=e.cloneNode=e.getRootNode=e.insertBefore=e.removeChild=e.replaceChild=c.attachShadow=c.createShadowRoot=c.getElementsByClassName=c.getElementsByTagName=
c.getElementsByTagNameNS=c.append=c.remove=c.before=c.after=c.prepend=c.querySelector=c.querySelectorAll=c.requestPointerLock=c.setAttribute=c.removeAttribute=c.removeAttributeNS=c.removeAttributeNode=c.replaceWith=c.insertAdjacentElement=c.insertAdjacentText=c.insertAdjacentHTML=l.focus=l.click=B.sendBeacon=R.open=function(){}}catch(v){}delete a.AnimationWorklet;delete a.Audio;delete a.AudioContext;delete a.Blob;delete a.CSS;delete a.CustomElementRegistry;delete a.CustomEvent;delete a.DOMImplementation;
delete a.DOMParser;delete a.Event;delete a.FormData;delete a.Image;delete a.JSON;delete a.LayoutWorklet;delete a.MutationObserver;delete a.Navigator;delete a.PaintWorklet;delete a.Proxy;delete a.Range;delete a.Request;delete a.Response;delete a.ServiceWorker;delete a.SharedWorker;delete a.Storage;delete a.URL;delete a.WebAssembly;delete a.WebSocket;delete a.Worker;delete a.XMLHttpRequest;delete a.XMLHttpRequestUpload;delete a.XMLSerializer;delete a.XSLTProcessor;delete a.fetch;delete a.close;delete a.open;
delete a.alert;delete a.confirm;delete a.eval;delete a.localStorage;delete a.postMessage;delete a.prompt;delete a.stop;delete a.customElements;delete a.navigator;delete e.textContent;delete b.cookie;delete b.body;delete B.serviceWorker;delete c.innerHTML;delete c.outerHTML;delete l.innerText;delete l.outerText;delete d.Event;for(var r in d)if("runtime"==r)for(var t in d.runtime)"function"===typeof d.runtime[t]&&"connect"!==t&&(d.runtime[t]=function(){});else if("object"===typeof d[r])try{h.defineProperty(d,
r,{configurable:!1,enumerable:!1,writable:!1,value:{}})}catch(v){}q.call(a,"DOMContentLoaded",function(){O.call(chrome_windows,function(b){var c=a.innerWidth,d,e;216>a.innerHeight&&(e=216+(a.outerHeight-a.innerHeight));350>c&&(d=350+(350-c));P.call(chrome_windows,b.id,{width:d,height:e,focused:!0})});var b=Q.call(chrome_i18n,"pgen").split(";");n.set.call(f("hdr"),b[0]);n.set.call(f("pan").firstElementChild.childNodes[0],b[1]);n.set.call(f("gen"),b[2]);n.set.call(f("copy"),b[3]);q.call(f("gen"),"click",
u,!1);q.call(f("copy"),"click",J,!1);u()},!1)})();
