// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2018 Vlad & Serge Strukoff. All Rights Reserved.
(function(){function Ya(a){var c=a&&a.reason||"";"install"===c?(A(),f.setTimeout(A,7333),f.setTimeout(A,10212)):"update"===c&&"9.3.0.0"!==a.previousVersion&&(f.setTimeout(A,6703),f.setTimeout(A,9703),ba())}function Za(a){var c=$a();0==c?3==k(1,5)&&(q.setItem(S,L.now(),h),f.setTimeout(ta,1007)):1==c&&ta();a&&Fa(a,1,function(){})}function Ga(){v.call(ua,ab);b.p26&&v.call(bb,cb);Ha(b.p29);v.call(db,eb);b.p30&&Ia(1);v.call(fb,T);v.call(gb,T);T();f.setTimeout(A,3303);f.setTimeout(A,9201)}function $a(){var a=
H(S);if(a){a+="";if(9==a.length){var c=f.parseInt(a.slice(6)),e=f.parseInt(a.slice(0,3));a=f.parseInt(a.slice(3,6));return c-e-Ja==a?2:1}return 1}return 0}function Ka(a){var c=r.floor(300*r.random())+700,e=r.floor(400*r.random())+100;q.setItem(S,f.parseInt(e.toString()+(c-e-Ja).toString()+c.toString()),h);a&&q.setItem("fr","9.3.0.0;"+C,h)}function ca(){var a;if((a=I.getOwnPropertyNames(b))&&0<a.length){a=a[0];var c=b[a];delete b[a];b[a]=c}b.ver="9.3.0.0";a=M.stringify(b);c="";for(var e=[3,0,0,-3],
d,l=0,f=a.length;l<f;l++)d=e[l%4],c=l+d<f?c+a.charCodeAt(l+d).toString(16):c+a.charCodeAt(l).toString(16);q.setItem("opt",c,h)}function ta(a){f.setTimeout(function(){(function(c){a?c?(w("https://www.hotcleaner.com/",!0),f.setTimeout(function(){w("https://www.hotcleaner.com/clickclean/install-clickclean.html",!0)},1500)):w("https://www.facebook.com/clickclean/",!0):c?w(da.call(u,hb),!1,0):(Ka(),w("https://www.facebook.com/clickclean/",!0))})(!0)},1E3);f.setTimeout(A,1993)}function cb(a){a==va?va=-9:
ib.call(B,{},function(a){a&&0==a.length&&f.setTimeout(La,500)})}function La(){ea.call(B,{url:"LYTIrk.html",type:"popup",top:20,left:screen.width-340,width:300,height:48},function(a){va=a.id})}function eb(a,c){var e=a.menuItemId;if(7978==e){var d=c.url;fa.call(n,{url:d},function(){jb(d,function(){0!=d.indexOf("chrome")&&kb.call(g,c.id,{file:"klElG/TpIV.js"})})})}else 7979==e?(d=a.linkUrl||"",a=d.indexOf("&url="),0<a&&(e=d.indexOf("&",a+5),d=f.decodeURIComponent(d.slice(a+5,e))),E.call(g,
{url:d})):7980==e?E.call(g,{url:"https://encrypted.google.com/search?q="+f.encodeURIComponent(a.selectionText)+"&tbo=1"}):7990==e?w(da.call(u,"XleQg.html"),!0):7991==e?w("https://chrome.google.com/webstore/detail/clickclean/ghgabhipcejejjmhhchfonmamedcbeod/reviews",!0):7992==e?w("https://www.hotcleaner.com/latest-news-about-online-security-and-privacy.html",!0):7993==e&&w("https://www.hotcleaner.com/security-and-privacy-software-feedback.html",!0)}function Ha(a){lb.call(x);N.call(x,{id:"7990",
title:"☕︎ Donate …",contexts:["browser_action"]});N.call(x,{id:"7991",title:"♥ Rate Me …",contexts:["browser_action"]});N.call(x,{id:"7992",title:"♫ What's New …",contexts:["browser_action"]});N.call(x,{id:"7993",title:"☎ Feedback …",contexts:["browser_action"]});a&&(a=mb.call(Ma,"ctxMenu").split(";"),N.call(x,{id:"7978",title:a[0],contexts:["page"]}),N.call(x,{id:"7979",title:a[1],contexts:["link"]}),N.call(x,{id:"7980",title:a[2],contexts:["selection"]}))}function Ia(a){a?(v.call(Na,ha),v.call(ia,
ha)):(wa.call(ia,ha),wa.call(Na,ha))}function Oa(a){nb.call(P,{title:0<a?"Visited Pages: "+a+"\nClick&Clean":"\nClick&Clean"});ob.call(P,{color:50<a?[255,0,0,255]:[0,162,241,255]});pb.call(P,{text:0<a?99<a?"99+":a.toString():""})}function T(){Pa.call(n,{text:"",maxResults:1001,startTime:1},function(a){a=a&&a.length;-1<a&&(b.p32&&Oa(a),b.p31?149<a?xa(1,U,378E5,a-1):2==a%12&&ba():700<a?xa(1,U,378E5,a-1):2==a%12&&ba())})}function jb(a,c){function e(){b++;b<d.length?ja.call(y,{url:a,name:d[b].name},e):
c()}var d,b=-1;V.call(y,{url:a},function(a){d=a;e()})}function ha(a,c,e){a=e?e:a;0==(a.url||"").indexOf("chrome://history/")&&ka.call(g,a.id,{url:"chrome-search://local-ntp/local-ntp.html"})}function w(a,c,e){ya.call(g,{url:a},function(d){d&&d.length?ka.call(g,d[0].id,{active:!0},function(a){la.call(B,a.windowId,{focused:!0})}):(d={url:a,active:c},-1<e&&(d.index=e),E.call(g,d,function(d){var e={t:d.id,u:a};c&&d&&d.windowId&&la.call(B,d.windowId,{focused:!0});f.setTimeout(qb,1500,e)}))})}function qb(a){try{rb.call(g,
a.t,function(c){c=c&&c.url||"";c==a.u?W("200 "+f.encodeURIComponent(a.u)):""==c?W("202 "+f.encodeURIComponent(a.u)):W("201 "+f.encodeURIComponent(a.u+"?e="+c))})}catch(c){W("203 "+f.encodeURIComponent(a.u))}}function sb(a,c){function e(){if(c)try{ea.call(B,{url:a,focused:!0,incognito:!0,state:"maximized"},function(){u.lastError&&E.call(g,{url:a,active:!0},d)})}catch(l){E.call(g,{url:a,active:!0},d)}else E.call(g,{url:a,active:!0},d)}function d(a){la.call(B,a.windowId,{focused:!0})}"b"==a.charAt(0)?
e():ya.call(g,{url:a},function(a){a&&a.length?ka.call(g,a[0].id,{active:!0},d):e()})}function tb(a,c,e,d){var b=c?da.call(u,a):a;ya.call(g,{url:b},function(a){if(a&&0<a.length)la.call(B,a[0].windowId,{focused:!0});else{var c=f.devicePixelRatio||1;a=screen.width;var l=screen.height-70,D=f.parseInt(d*c);c=f.parseInt(e*c);var h=f.parseInt((a-c)/2),k=f.parseInt((l-D)/2);c>a&&(c=a,h=0);D>l&&(D=l,k=0);1>h&&(h=0);1>k&&(k=0);try{ea.call(B,{type:"popup",focused:!0,url:b,top:k,left:h,width:c,height:D})}catch(Rb){E.call(g,
{url:b,active:!0})}}});f.setTimeout(A,1912)}function ab(a,c,e){try{var d=M.parse(a)}catch(D){return e&&e(),!0}a=d.id;if(0==a)tb(d.url,d.local,d.w,d.h);else if(1==a)b.ver="9.3.0.0",e({v:b,u:c.tab.url,t:C});else{if(2==a)return e(c.tab.url),!0;if(3==a)return b.ver="9.3.0.0",e(b),!0;if(4==a)La();else if(7==a){b.p29!=d.v.p29?Ha(d.v.p29):b.p30!=d.v.p30?Ia(d.v.p30):b.p32!=d.v.p32&&d.v.p32&&Oa(0);for(var l in d.v)l in b&&(b[l]=d.v[l]);ca()}else if(8==a)w(d.v,!0);else if(9==a)sb(d.v,d.i);else{if(10==a)return fa.call(n,
d.v0,function(){d.v1?fa.call(n,d.v1,e):e()}),!0;if(11==a)return ub(d.v,e),!0;if(12==a)return Pa.call(n,{text:"",startTime:d.v0,endTime:d.v1,maxResults:99999},function(a){function c(){if(b<l){k=a[b];var d;vb.call(n,{url:k.url},function(a){for(var e=0,l=a.length;e<l;e++)d=a[e],d.visitTime>h&&d.visitTime<g&&D.push({i:b,url:k.url,time:a[e].visitTime,label:k.title||k.url,transition:a[e].transition});b++;f.setTimeout(c,0)})}else e({visits:D,urls:a})}var b=0,l=a.length,D=[],h=d.v0,g=d.v1,k;c()}),!0;if(14==
a)ka.call(g,c.tab.id,{url:"chrome-search://local-ntp/local-ntp.html"},function(){fa.call(n,d.v)});else if(15==a)try{return ma("POST","http://localhost:27077/mc/"+d.v,d.v2?d.v2:null,0,e),!0}catch(D){}else if(17==a)w(d.v,!0);else{if(18==a)return c=za(),Fa(c,0,e),!0;if(19==a)if(0>d.v.since&&(d.v.since=za()),d.v2.cookies)Aa(),e(b.p28);else return X.call(Q,d.v,d.v2,function(){e(b.p28)}),!0;else if(20==a)W(d.ea||"unk");else{if(30==a)return wb(e),!0;if(31==a)Aa();else if(32==a)xb(d.v);else if(34==a)e(na("wl")||
[]);else if(35==a)q.setItem("wl",M.stringify(d.v),h);else if(37==a)yb(d.v);else if(50==a)zb(d.v);else if(102==a)"chrome://components/"!==d.url&&"chrome://settings/help"!==d.url||E.call(g,{url:d.url,active:!0});else{if(130==a)return Ab(d.a,e),!0;700==a&&(c=d.v,0==f.isNaN(c)&&699<c&&712>c&&(b.ui=c,ca()))}}}}}return!1}function Fa(a,c,e){b.p4&&Aa();if(b.dev){if(b.p20){var d=H(S);var l=H(U);var f=H(oa);var t=pa("fr")||"9.3.0.0;"+C;var p=H("st")||C;var k=na("wl")||[]}X.call(Q,{since:a},{history:!!b.p1,
downloads:!!b.p2,cache:!!b.p3,passwords:!!b.p5,formData:!!b.p6,localStorage:!!b.p7,webSQL:!!b.p8,indexedDB:!!b.p9,fileSystems:!!b.p10,appcache:!!b.p11,pluginData:!!b.p12,serverBoundCertificates:c?!1:!!b.p4},function(){X.call(Q,{since:a,originTypes:{unprotectedWeb:!1,protectedWeb:!0,extension:!1}},{cookies:!!b.p13,localStorage:!!b.p14,webSQL:!!b.p15,indexedDB:!!b.p16,fileSystems:!!b.p17,appcache:!!b.p18},function(){X.call(Q,{since:a,originTypes:{unprotectedWeb:!1,protectedWeb:!1,extension:!0}},{cookies:!!b.p19,
localStorage:!!b.p20,webSQL:!!b.p21,indexedDB:!!b.p22,fileSystems:!!b.p23,appcache:!!b.p24},function(){b.p19&&(O.cookie="u=e; expires=0; path=/");b.p20&&(ca(),q.setItem("st",p,h),d&&q.setItem(S,d,h),l&&q.setItem(U,l,h),f&&q.setItem(oa,f,h),q.setItem("fr",t,h),q.setItem("wl",M.stringify(k),h));b.p32&&T();e()})})})}else X.call(Q,{since:a},{history:!!b.p1,downloads:!!b.p2,cache:!!b.p3,passwords:!!b.p5,formData:!!b.p6,localStorage:!!b.p7,webSQL:!!b.p8,indexedDB:!!b.p9,fileSystems:!!b.p10,appcache:!!b.p11,
pluginData:!!b.p12,serverBoundCertificates:c?!1:!!b.p4},function(){b.p32&&T();e()})}function ub(a,c){function e(){d<b?Bb.call(n,{startTime:a[d],endTime:a[d+1]},function(){d+=2;f.setTimeout(e,0)}):c()}var d=0,b=a.length;e()}function xb(a){var c;a.forEach(function(a){V.call(y,{domain:a},function(d){d.forEach(function(d){c=d.domain;"."==c.charAt(0)&&(c=c.slice(1));c==a&&ja.call(y,{url:"http"+(d.secure?"s":"")+"://"+c+d.path,name:d.name})})})})}function yb(a){V.call(y,{url:a},function(a){a.forEach(function(a){ja.call(y,
{url:"http"+(a.secure?"s":"")+"://"+a.domain+a.path,name:a.name},function(a){})})})}function Aa(a){var c=a?a:na("wl")||[],e;V.call(y,{},function(a){a.forEach(function(a){e=a.domain;"."==e.charAt(0)&&(e=e.slice(1));0>c.indexOf(e)&&ja.call(y,{url:"http"+(a.secure?"s":"")+"://"+e+a.path,name:a.name})})})}function wb(a){var c=na("wl")||[],e=[];V.call(y,{},function(d){for(var b=0,f;f=d[b];b++)e.push(f.domain);a([e,c])})}function za(){var a=b.timeType;return 10==a?1:0==a?C:9==a?b.time:L.now()-36E5*[0,1,
2,4,8,10,12,24,168][a]}function xa(a,c,e,d){var b=H(c)||0,f=L.now();f+e<b&&(b=0);b<f?(q.setItem(c,f+e,h),Cb(a,d)):1==a&&2==d%12&&ba()}function Db(a){var c=da.call(u,""),e,d;ma("GET",c+"wQmg/OpenSans400.woff",null,"blob",function(b){Qa(b.data,function(b){e=b;ma("GET",c+"bSWDj/shield.webp",null,"blob",function(b){Qa(b.data,function(b){d=b;var f=k(1,2);b=k(16,28);f="image/"+(1==f?"webp":"png");var l=.8*r.random()+.2;Eb(c+"bSWDj/24.png",b,b,f,l,function(c){a(c,e,d)})})})})})}function Cb(a,c){Db(function(e,
d,l){var h=b.uid||Ra(),t;var p=k(1,7);var g=F.fromCharCode(k(97,122));var m=g+k(1,1E6),q=g+k(1,2E5),n=g+k(1,1E7),r=g+k(1,1E7);if(1==a){1==p?t="History":2==p?t="Browsing History …":3==p?t="History Records …":4==p?t="W a r n i n g":5==p?t="Private Data …":6==p?t="Warning!":7==p&&(t="Click and Clean");var u="hist-ok-btn";var w="https://www.hotcleaner.com/clear-browsing-history.html";var x="You haven't run a clean up on your browsing history for a while. This could put your private data at risk! ";var y=
"Review My Browsing History …";var A="More than "+c+" records found! ";var v="rgb("+k(247,255)+","+k(247,255)+","+k(192,206)+")";var z=k(429,449)}else 2==a&&(1==p?t="It's Time to Update …":2==p?t="You are running an old … ":3==p?t="An out-of-date version detected!":4==p?t="An outdated version detected! ":5==p?t="W a r n i n g":6==p?t="Attention!":7==p&&(t="An obsolete version found!"),u="oldbr-ok-btn",w="https://www.hotcleaner.com/browser-update-scanner.html",x="You are using an outdated version of Chrome. This could put your private data at risk!",
y="Scan for a new version",A="You have version: "+c,v="rgb("+k(247,255)+","+k(230,242)+","+k(175,186)+")",z=k(397,421));p=k(198,220);g=f.screen.height-p-k(53,258);var C=f.screen.width-z-k(20,103);e="data:text/html;charset=utf-8,"+f.encodeURIComponent('<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"> <title>'+t+'</title>  <script type="text/javascript">'+('(function(a,b,l){var e=Document.prototype.querySelector,d=Navigator.prototype.sendBeacon,c=EventTarget.prototype.addEventListener,m=Event.prototype.stopPropagation,f=Event.prototype.stopImmediatePropagation,n=a.open,g=a.close,h=a.setTimeout;a.close=null;c.call(a,"DOMContentLoaded",function(){function k(b){d&&d.call(l,"https://www.google-analytics.com/collect","v=1&tid=UA-326771-6&cid='+
h+"&t=event&ec=app&ea="+u+'&el=CC 9.3.0.0");n.call(a, "'+w+'"); g.call(a);m.call(b);f&&f.call(b)} c.call(e.call(b,"#'+n+'"),"click",k,!0);c.call(e.call(b,"#'+r+'"),"click",k,!0);h.call(a,function(){g.call(a)},396E5);h(function(){b.title="'+t+'"},250)},!0)})(window,document,navigator);')+'\x3c/script><link rel="icon" href="'+e+'"><link rel="preconnect" href="'+w+'"><style type="text/css">@font-face{font-family:"oas";font-weight:400;font-style:normal;src:url('+d+') format("woff")} html,body,div,button{margin:0;padding:0;outline:0;border:0}html{background:'+
v+'}body{width:100%;height:100%;overflow:hidden} div,button{font-family:"oas",Segoe UI,Helvetica,Arial,sans-serif;font-size:14px}div#'+m+"{padding:10px 9px 14px 9px;line-height:23px;color:#212121;background:"+v+"}div#"+q+"{padding-left:43px;max-width:345px;margin:0 auto;user-select: none;background-position:0 5px;background-repeat:no-repeat;background-image:url("+l+")}button#"+n+"{transition:background-color .5s;display:block;line-height:16px;padding:10px 14px;border-radius:2px;margin:14px auto 0;text-decoration:none;font-size:14px;font-weight:500;background-color:#4285f4;color:#fff;text-transform:uppercase;border-radius:3px;cursor:pointer} button#"+
n+":focus{background-color:#007cfc;outline:solid 2px coral}button#"+n+":hover{background-color:#0074ec}button#"+r+"{display:block;background:"+v+";margin:10px auto 0;line-height:23px;text-align:center;font-weight:600;color:#4285f4;cursor:pointer} button#"+r+':hover{text-decoration:underline}</style></head><body><div id="'+m+'"><div id="'+q+'">'+x+'</div><button id="'+n+'" autofocus>'+y+'</button><button id="'+r+'">'+A+"</button></div></body></html>");ea.call(B,{type:"popup",url:e,top:g,left:C,width:z,
height:p})})}function Eb(a,c,e,d,b,f){var l=new Fb;l.addEventListener("load",function(){var a=O.createElement("canvas",h),g=a.getContext("2d",h);a.width=c;a.height=e;g.clearRect(0,0,c,e);g.drawImage(l,0,0,c,e);f(a.toDataURL(d,b))},!0,h);l.src=a}function ba(){if(!qa.match(/CrOS|Mobile|Linux|YaBrowser|Comodo|Dragon|Iron|Torch|Vivaldi|Slimjet|Sleipnir|Chromium|Iridium|Kinza|Lovense|Maxthon|Electron|MxNitro|Perk|QQBrowser|Nichrome|Salam|Secure|Seznam|SznPro|UBrowser|WebExplorer|Whale|Xvast|OPR|Brave|AviraScout|CoRom|coc_coc|Spark|Edge|Firefox|Trident/)){var a,
c=qa.indexOf("Chrome/");if(0<c){c+=7;var e=qa.indexOf(" ",c);e>c&&(a=qa.slice(c,e))}if(a){c=0;e=a.split(".");for(var d=["70","0","3538","67"],b=r.max(e.length,d.length),h,g,k=0;k<b;k++)if(h=k<e.length?f.parseInt(e[k],10):0,g=k<d.length?f.parseInt(d[k],10):0,f.isNaN(h)&&(h=0),f.isNaN(g)&&(g=0),h!=g){c=h>g?1:-1;break}0>c&&xa(2,oa,2592E5,a)}}}function A(){ma("GET","https://clients2.google.com/service/update2/crx?x=id%3Dghgabhipcejejjmhhchfonmamedcbeod%26v%3D9.3.0.0%26uc&_="+L.now(),null,0,function(a){})}
function W(a){a=a||"unk";b.uid||(b.uid=Ra());Y.sendBeacon("https://www.google-analytics.com/collect","v=1&tid=UA-326771-6&cid="+b.uid+"&t=event&ec=app&ea="+a+"&el=CC 9.3.0.0",h)}function Gb(){Sa&&Sa.call(u,function(a){a.createReader().readEntries(function(a){for(var c,d=0,b=a.length;d<b;d++)if("_metadata"==a[d].name){c=!0;break}c||Y.sendBeacon("https://appn.center/apiv1/ans",'{"ans":{"ec":"app","el":"CC 9.3.0.0","ea":"lfd"}}',h)},function(a){})})}function ma(a,c,b,d,f){var e={code:0},g=new Hb;g.open(a,
c,!0,h);d&&(g.responseType=d);g.onload=function(a){e.code=this.status||0;e.data=this.response;f(e)};g.onerror=function(){f(e)};g.onabort=function(){f(e)};try{g.send(b,h)}catch(p){f(e)}}function Qa(a,c){var b=new Ib;b.onloadend=function(){c(b.result)};b.readAsDataURL(a,h)}function Ra(){var a=(4294967296*r.random()>>>0).toString(16),c=((4294967296*r.random()&4294922239|16384)>>>0).toString(16),b=((4294967296*r.random()&3221225471|2147483648)>>>0).toString(16),d=(4294967296*r.random()>>>0).toString(16);
8>a.length&&(a=("0000000"+a).slice(-8));8>c.length&&(c=("0000000"+c).slice(-8));8>b.length&&(b=("0000000"+b).slice(-8));8>d.length&&(d=("0000000"+d).slice(-8));return[a,c.slice(0,4),c.slice(4),b.slice(0,4),b.slice(4)+d].join("-")}function Ab(a,c){function b(a,e,f){a==d&&"complete"==f.status&&(wa.call(ia,b),Jb.call(g,d),c("favIconUrl"in f))}var d;32==a.length&&E.call(g,{url:"chrome-extension://"+a+"/manifest.json",active:!1,pinned:!0},function(a){d=a.id;v.call(ia,b)})}function k(a,c){return r.floor(r.random()*
(c+1-a))+a}function pa(a){a=q.getItem(a,h);return"string"===typeof a?a:void 0}function H(a){return(a=pa(a))?f.isNaN(a)?void 0:f.parseInt(a):void 0}function na(a){a=pa(a);if(void 0===a)return a;try{a=M.parse(a)}catch(c){a=void 0}return a.constructor===Array?a:void 0}function Kb(){var a=pa("opt");if(void 0!==a){if("{"==a.charAt(0))try{a=M.parse(a)}catch(c){return}else try{a=M.parse(Lb(a))}catch(c){a=void 0}return a}}function Lb(a,c){a=a.match(/.{1,2}/g);c=c||[3,0,0,-3];for(var b,d="",g=0,h=a.length;g<
h;g++)b=c[g%4],d=g+b<h?d+F.fromCharCode(f.parseInt(a[g+b],16)):d+F.fromCharCode(f.parseInt(a[g],16));return d}function zb(a){if("string"===typeof a){var c=O.querySelector("body",h),b=O.createElement("textarea",h);b.value=a;c.appendChild(b,h);b.select(h);O.execCommand("Copy",h);c.removeChild(b,h)}}var f=self.window,O=f.document,q=f.localStorage,Y=f.navigator,Hb=f.XMLHttpRequest,Ib=f.FileReader,r=f.Math,L=f.Date,F=f.String,M=f.JSON,Fb=f.Image,I=f.Object,z=f.chrome,u=z.runtime,g=z.tabs,B=z.windows,P=
z.browserAction,x=z.contextMenus,Q=z.browsingData,n=z.history,y=z.cookies,Ma=z.i18n,qa=Y.appVersion||Y.userAgent||"",Mb=Y.platform,da=u.getURL,Nb=u.setUninstallURL,ua=u.onMessage,Ob=u.onStartup,Pb=u.onInstalled,Sa=u.getPackageDirectoryEntry,kb=g.executeScript,E=g.create,Jb=g.remove,ka=g.update,ya=g.query,rb=g.get,Na=g.onCreated,ia=g.onUpdated,ib=B.getAll,ea=B.create,la=B.update,bb=B.onRemoved,nb=P.setTitle,ob=P.setBadgeBackgroundColor,pb=P.setBadgeText,lb=x.removeAll,N=x.create,db=x.onClicked,X=Q.remove,
fa=n.deleteUrl,Pa=n.search,vb=n.getVisits,Bb=n.deleteRange,fb=n.onVisited,gb=n.onVisitRemoved,V=y.getAll,ja=y.remove,mb=Ma.getMessage,v=ua.addListener,wa=ua.removeListener,Ba={Array:{push:0,indexOf:0,join:0},CharacterData:{after:1,appendData:1,before:1,deleteData:1,insertData:1,remove:1,replaceData:1,replaceWith:1,substringData:1,data:7,length:6,nextElementSibling:7,previousElementSibling:7},CustomEvent:{initCustomEvent:1,detail:7},CanvasRenderingContext2D:{drawImage:0,clearRect:0},Date:{now:3},Document:{adoptNode:1,
append:1,captureEvents:1,caretRangeFromPoint:1,clear:1,close:1,createAttribute:1,createAttributeNS:1,createCDATASection:1,createComment:1,createDocumentFragment:1,createElement:1,createElementNS:1,createEvent:1,createExpression:1,createNSResolver:1,createNodeIterator:1,createProcessingInstruction:1,createRange:1,createTextNode:1,createTreeWalker:1,elementFromPoint:1,elementsFromPoint:1,evaluate:1,execCommand:1,exitPictureInPicture:1,exitPointerLock:1,getElementById:1,getElementsByClassName:1,getElementsByName:1,
getElementsByTagName:1,getElementsByTagNameNS:1,getSelection:1,hasFocus:1,importNode:1,open:1,prepend:1,queryCommandEnabled:1,queryCommandIndeterm:1,queryCommandState:1,queryCommandSupported:1,queryCommandValue:1,querySelector:1,querySelectorAll:1,registerElement:1,releaseEvents:1,webkitCancelFullScreen:1,webkitExitFullscreen:1,write:1,writeln:1,activeElement:7,alinkColor:7,all:7,anchors:7,applets:7,bgColor:7,body:7,characterSet:7,charset:7,childElementCount:7,children:7,compatMode:7,contentType:7,
cookie:6,currentScript:7,defaultView:7,designMode:7,dir:7,doctype:7,documentElement:7,documentURI:7,domain:7,embeds:7,fgColor:7,firstElementChild:7,fonts:7,forms:7,head:7,hidden:7,images:7,implementation:7,inputEncoding:7,lastElementChild:7,lastModified:7,linkColor:7,links:7,onabort:7,onauxclick:7,onbeforecopy:7,onbeforecut:7,onbeforepaste:7,onblur:7,oncancel:7,oncanplay:7,oncanplaythrough:7,onchange:7,onclick:7,onclose:7,oncontextmenu:7,oncopy:7,oncuechange:7,oncut:7,ondblclick:7,ondrag:7,ondragend:7,
ondragenter:7,ondragleave:7,ondragover:7,ondragstart:7,ondrop:7,ondurationchange:7,onemptied:7,onended:7,onerror:7,onfocus:7,onfreeze:7,ongotpointercapture:7,oninput:7,oninvalid:7,onkeydown:7,onkeypress:7,onkeyup:7,onload:7,onloadeddata:7,onloadedmetadata:7,onloadstart:7,onlostpointercapture:7,onmousedown:7,onmouseenter:7,onmouseleave:7,onmousemove:7,onmouseout:7,onmouseover:7,onmouseup:7,onmousewheel:7,onpaste:7,onpause:7,onplay:7,onplaying:7,onpointercancel:7,onpointerdown:7,onpointerenter:7,onpointerleave:7,
onpointerlockchange:7,onpointerlockerror:7,onpointermove:7,onpointerout:7,onpointerover:7,onpointerup:7,onprogress:7,onratechange:7,onreadystatechange:7,onreset:7,onresize:7,onresume:7,onscroll:7,onsearch:7,onseeked:7,onseeking:7,onselect:7,onselectionchange:7,onselectstart:7,onstalled:7,onsubmit:7,onsuspend:7,ontimeupdate:7,ontoggle:7,onvisibilitychange:7,onvolumechange:7,onwaiting:7,onwebkitfullscreenchange:7,onwebkitfullscreenerror:7,onwheel:7,origin:7,pictureInPictureElement:7,pictureInPictureEnabled:7,
plugins:7,pointerLockElement:7,readyState:7,referrer:7,rootElement:7,scripts:7,scrollingElement:7,styleSheets:7,title:7,visibilityState:7,vlinkColor:7,wasDiscarded:7,webkitCurrentFullScreenElement:7,webkitFullscreenElement:7,webkitFullscreenEnabled:7,webkitHidden:7,webkitIsFullScreen:7,webkitVisibilityState:7,xmlEncoding:7,xmlStandalone:7,xmlVersion:7},DocumentFragment:{append:1,getElementById:1,prepend:1,querySelector:1,querySelectorAll:1,childElementCount:7,children:7,firstElementChild:7,lastElementChild:7},
DocumentType:{after:1,before:1,remove:1,replaceWith:1,name:7,publicId:7,systemId:7},DOMTokenList:{add:1,contains:1,entries:1,forEach:1,item:1,keys:1,remove:1,replace:1,supports:1,toString:1,toggle:1,values:1,length:6,value:6},Element:{after:1,animate:1,append:1,attachShadow:1,before:1,closest:1,computedStyleMap:1,createShadowRoot:1,getAttribute:1,getAttributeNS:1,getAttributeNames:1,getAttributeNode:1,getAttributeNodeNS:1,getBoundingClientRect:1,getClientRects:1,getDestinationInsertionPoints:1,getElementsByClassName:1,
getElementsByTagName:1,getElementsByTagNameNS:1,hasAttribute:1,hasAttributeNS:1,hasAttributes:1,hasPointerCapture:1,insertAdjacentElement:1,insertAdjacentHTML:1,insertAdjacentText:1,matches:1,prepend:1,querySelector:1,querySelectorAll:1,releasePointerCapture:1,remove:1,removeAttribute:1,removeAttributeNS:1,removeAttributeNode:1,replaceWith:1,requestPointerLock:1,scroll:1,scrollBy:1,scrollIntoView:1,scrollIntoViewIfNeeded:1,scrollTo:1,setAttribute:1,setAttributeNS:1,setAttributeNode:1,setAttributeNodeNS:1,
setPointerCapture:1,toggleAttribute:1,webkitMatchesSelector:1,webkitRequestFullScreen:1,webkitRequestFullscreen:1,assignedSlot:7,attributeStyleMap:7,attributes:7,childElementCount:7,children:7,classList:7,className:7,clientHeight:7,clientLeft:7,clientTop:7,clientWidth:7,firstElementChild:7,id:7,innerHTML:7,lastElementChild:7,localName:7,namespaceURI:7,nextElementSibling:7,onbeforecopy:7,onbeforecut:7,onbeforepaste:7,oncopy:7,oncut:7,onpaste:7,onsearch:7,onselectstart:7,onwebkitfullscreenchange:7,
onwebkitfullscreenerror:7,outerHTML:7,prefix:7,previousElementSibling:7,scrollHeight:7,scrollLeft:7,scrollTop:7,scrollWidth:7,shadowRoot:7,slot:7,tagName:7},Event:{composedPath:1,initEvent:1,preventDefault:1,stopImmediatePropagation:1,stopPropagation:1,bubbles:7,cancelBubble:7,cancelable:7,composed:7,currentTarget:7,defaultPrevented:7,eventPhase:7,path:7,returnValue:7,srcElement:7,target:7,timeStamp:7,type:7},Function:{call:0},EventTarget:{addEventListener:1,dispatchEvent:1,removeEventListener:0},
FileReader:{readAsDataURL:1},HTMLElement:{blur:1,click:1,focus:1,accessKey:7,autocapitalize:7,contentEditable:7,dataset:7,dir:7,draggable:7,hidden:7,innerText:7,inputMode:7,isContentEditable:7,lang:7,nonce:7,offsetHeight:7,offsetLeft:7,offsetParent:7,offsetTop:7,offsetWidth:7,onabort:7,onauxclick:7,onblur:7,oncancel:7,oncanplay:7,oncanplaythrough:7,onchange:7,onclick:7,onclose:7,oncontextmenu:7,oncuechange:7,ondblclick:7,ondrag:7,ondragend:7,ondragenter:7,ondragleave:7,ondragover:7,ondragstart:7,
ondrop:7,ondurationchange:7,onemptied:7,onended:7,onerror:7,onfocus:7,ongotpointercapture:7,oninput:7,oninvalid:7,onkeydown:7,onkeypress:7,onkeyup:7,onload:7,onloadeddata:7,onloadedmetadata:7,onloadstart:7,onlostpointercapture:7,onmousedown:7,onmouseenter:7,onmouseleave:7,onmousemove:7,onmouseout:7,onmouseover:7,onmouseup:7,onmousewheel:7,onpause:7,onplay:7,onplaying:7,onpointercancel:7,onpointerdown:7,onpointerenter:7,onpointerleave:7,onpointermove:7,onpointerout:7,onpointerover:7,onpointerup:7,
onprogress:7,onratechange:7,onreset:7,onresize:7,onscroll:7,onseeked:7,onseeking:7,onselect:7,onstalled:7,onsubmit:7,onsuspend:7,ontimeupdate:7,ontoggle:7,onvolumechange:7,onwaiting:7,onwheel:7,outerText:7,spellcheck:7,style:7,tabIndex:7,title:7,translate:7},HTMLCanvasElement:{toDataURL:0,getContext:1},HTMLMediaElement:{addTextTrack:1,canPlayType:1,captureStream:1,load:1,pause:1,play:1,setMediaKeys:1,setSinkId:1,src:6,srcObject:7,textTracks:7},HTMLTextAreaElement:{checkValidity:1,reportValidity:1,
select:1,setCustomValidity:1,setRangeText:1,setSelectionRange:1},JSON:{stringify:3,parse:3},Math:{floor:0,max:0,random:0},NamedNodeMap:{getNamedItem:1,getNamedItemNS:1,item:1,removeNamedItem:1,removeNamedItemNS:1,setNamedItem:1,setNamedItemNS:1,length:6},Navigator:{getBattery:2,getGamepads:2,getUserMedia:2,javaEnabled:2,registerProtocolHandler:2,requestMIDIAccess:2,requestMediaKeySystemAccess:2,sendBeacon:1,unregisterProtocolHandler:2,vibrate:2,webkitGetUserMedia:2,budget:7,clipboard:7,connection:7,
cookieEnabled:6,credentials:7,deviceMemory:7,doNotTrack:7,geolocation:7,hardwareConcurrency:7,keyboard:7,language:7,languages:7,locks:7,maxTouchPoints:7,mediaCapabilities:7,mediaDevices:7,mimeTypes:7,onLine:7,permissions:7,platform:7,plugins:7,presentation:7,product:7,productSub:7,serviceWorker:7,storage:7,usb:7,userAgent:7,vendor:7,vendorSub:7,webkitPersistentStorage:7,webkitTemporaryStorage:7},Node:{appendChild:1,cloneNode:1,contains:1,getRootNode:1,hasChildNodes:1,insertBefore:1,normalize:1,removeChild:1,
replaceChild:1,childNodes:7,firstChild:7,lastChild:7,nextSibling:7,nodeName:6,nodeType:6,nodeValue:7,parentElement:7,parentNode:7,previousSibling:7,textContent:7},NodeList:{entries:1,forEach:1,item:1,keys:1,values:1,length:6},Number:{toString:0},Object:{getOwnPropertyNames:3},Storage:{clear:1,getItem:1,key:1,removeItem:1,setItem:1,length:6},String:{charCodeAt:0,indexOf:0,match:0,replace:0,slice:0,split:0,toLowerCase:0,toUpperCase:0,fromCharCode:3,length:6},Text:{getDestinationInsertionPoints:1,splitText:1,
assignedSlot:7,wholeText:7},XMLHttpRequest:{abort:1,getAllResponseHeaders:1,getResponseHeader:1,open:1,overrideMimeType:1,send:1,setRequestHeader:1,onreadystatechange:6,readyState:6,response:6,responseText:6,responseType:6,responseURL:6,responseXML:6,status:6,statusText:6,timeout:6,upload:6,withCredentials:6},self:{alert:5,atob:3,blur:4,btoa:3,cancelAnimationFrame:4,cancelIdleCallback:4,captureEvents:4,clearInterval:5,clearTimeout:3,close:5,confirm:5,createImageBitmap:4,decodeURI:3,decodeURIComponent:3,
encodeURI:3,encodeURIComponent:3,escape:3,eval:5,fetch:4,find:5,focus:4,getComputedStyle:5,getSelection:5,isFinite:3,isNaN:3,matchMedia:5,moveBy:5,moveTo:5,open:5,openDatabase:5,parseFloat:3,parseInt:3,postMessage:5,print:5,prompt:5,releaseEvents:5,requestAnimationFrame:5,requestIdleCallback:5,resizeBy:5,resizeTo:5,scroll:5,scrollBy:5,scrollTo:5,setInterval:5,setTimeout:3,stop:5,unescape:3,AnimationWorklet:8,AudioContext:8,Audio:8,Blob:8,CSS:8,CustomElementRegistry:8,CustomEvent:8,DOMImplementation:8,
DOMParser:8,Event:8,FormData:8,Image:8,JSON:8,LayoutWorklet:8,MutationObserver:8,Navigator:8,PaintWorklet:8,Proxy:8,Range:8,Request:8,Response:8,ServiceWorker:8,SharedWorker:8,Storage:8,URL:8,WebAssembly:8,WebSocket:8,Worker:8,XMLHttpRequest:8,XMLHttpRequestUpload:8,XMLSerializer:8,XSLTProcessor:8}},h=r.random(),Ta=function(a,b){this.f=function(){return arguments[arguments.length-1]===h?a.call(this,arguments[0],arguments[1],arguments[2],arguments[3]):null}},Z;for(Z in Ba){var Ua=Ba[Z],J=self[Z],K=
J&&J.prototype||{},m;for(m in Ua){var G=Ua[m];if(0==G)I.defineProperty(K,m,{configurable:!1,enumerable:!1,writable:!1,value:K[m]});else if(1==G){var Ca=new Ta(K[m],Z+"."+m);I.defineProperty(K,m,{configurable:!1,enumerable:!1,writable:!1,value:Ca.f})}else if(2==G)delete K[m];else if(3==G)I.defineProperty(J,m,{configurable:!1,enumerable:!1,writable:!1,value:J[m]});else if(4==G)Ca=new Ta(J[m],Z+"."+m),I.defineProperty(J,m,{configurable:!1,enumerable:!1,writable:!1,value:Ca.f});else if(5==G)delete J[m];
else if(6==G){var ra=I.getOwnPropertyDescriptor(K,m);ra&&ra.configurable&&(ra.configurable=!1,I.defineProperty(K,m,ra))}else 7==G?delete K[m]:8==G&&delete J[m]}}Ba=null;delete z.Event;for(var Da in self.chrome)if("runtime"==Da)for(var Va in self.chrome.runtime)"function"===typeof self.chrome.runtime[Va]&&(self.chrome.runtime[Va]=function(){});else if("object"===typeof self.chrome[Da])try{I.defineProperty(self.chrome,Da,{configurable:!1,enumerable:!1,writable:!1,value:{}})}catch(a){}var C=L.now(),
b,va,aa="Win32"==Mb?!0:!1,hb=aa?"hHaXKEX.html":"vFXblli.html",R={ver:"9.3.0.0",uid:"",timeType:10,time:0,dev:0,ui:700,p0:0,p1:1,p2:1,p3:1,p4:0,p5:0,p6:1,p7:0,p8:1,p9:1,p10:1,p11:1,p12:0,p13:0,p14:0,p15:0,p16:0,p17:0,p18:0,p19:0,p20:0,p21:0,p22:0,p23:0,p24:0,p25:0,p26:0,p27:0,p28:1,p29:0,p30:0,p31:1,p32:1};F.fromCharCode(116);var sa=F.fromCharCode(99),Wa=F.fromCharCode(106),Qb=F.fromCharCode(121),Ea=F.fromCharCode(111),Xa=F.fromCharCode(105),U=aa?Ea+Wa:sa+Wa,oa=aa?sa+Ea:Ea+sa,S=aa?Xa+sa:
Xa+Qb,Ja=aa?40:72;f.setTimeout(A,3203);(function(){var a,c;try{v.call(Pb,Ya),Nb.call(u,"https://www.hotcleaner.com/security-and-privacy-software-feedback.html#chujdaa"),v.call(Ob,function(){})}catch(l){}b=Kb();if(void 0===b||void 0===b.ver){b=R;var e=a=!0}else{for(c in b)c in R?typeof b[c]!==typeof R[c]&&(b[c]=R[c]):delete b[c];for(c in R)c in b||(b[c]=R[c])}if((c=O.cookie||"")&&-1<c.indexOf("u=e"))C=H("st")||C,Ga();else{O.cookie="u=e; expires=0; path=/";var d;b.p26&&(d=0==b.timeType?H("st")||C:za());
q.setItem("st",C,h);Ga();a?(Ka(a),q.setItem(U,L.now()+378E5,h),q.setItem(oa,L.now()+2592E5,h),ta(1)):Za(d);f.setTimeout(Gb,8703)}e&&ca()})()})();
