// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2018 Vlad & Serge Strukoff. All Rights Reserved.
(function(){function na(){function c(){var a=this.id;A!=a&&(A&&(D("#"+A).className="nav"),A=a,this.className="nav act",e(a))}function e(g,b){b=b||D("#box");if("menu0"==g)var c=[3,"red","close.png",0,7,0,"options1.png",18,3,"magenta","clear.png",1,7,0,"options1.png",18,7,0,"tabs1.png",2,3,"violet","cache.png",3,7,0,"trash1.png",4,3,"violet","history.png",5,7,0,"trash1.png",6,0,"blue",w?"quickscan.png":"extensions.png",w?8:7,3,"violet","downloads.png",9,7,0,"trash1.png",10,0,"choko","cookie.png",15,
7,0,"trash1.png",16,0,"seawave",w?"cleanup.png":"memory.png",w?12:13,3,"violet","security.png",14,0,"carbon","incognito.png",11,0,"teal","report.png",17,0,"magenta","options.png",18,7,0,"themes.png",19,0,"green","updates.png",20,0,"yellow","rate32.png",21];else if("menu1"==g)c=[3,"seawave","plugins.png",0,3,"green","extensions.png",1,3,"orange","experiments.png",2,3,"magenta","internals.png",3,0,"violet","dns.png",4,3,"violet","history.png",5,0,"violet","cache.png",6,0,"red","key.png",7,3,"blue",
"version.png",8,7,0,"arrow1.png",9,0,"red","conflicts.png",10,0,"teal","policies.png",11,0,"blue","releases.png",12,7,0,"calendar1.png",13,0,"blue","credits.png",14,0,"teal","bug.png",15];else if("menu2"==g)c=[3,"green","winsec.png",0,3,"blue","info.png",1,3,"red","uninstall.png",2,3,"violet","defragmenter.png",3,3,"magenta","sound.png",4,3,"marine","network.png",5,7,0,"connect.png",6,7,0,"wireless.png",7,3,"teal","devices.png",8,3,"violet","display.png",9,3,"blue","services.png",10,3,"seawave","directx.png",
11];else if("menu3"==g){F(G.call(l,"XleQg.html"));L.call(a);return}var e=0;g=O.call(M,g).split(";");for(var aa=Z.call(t),h,B,x,f,d,m,n,p,q,r,k=0;k<c.length;k+=4)n=k/4,d=c[k],m=c[k+1],p=c[k+2],n="i"+n,p="bSWDj/menu/"+p,r=g[c[k+3]],7>d?(q=0,h=v.call(t,"div"),B=v.call(t,"div"),f=v.call(t,"div"),x=new ba,m="btn "+m,2<d?(m+=" wide",h.className="btnBoxWide"):h.className="btnBox",B.id=n,B.className=m,x.className="icn",f.className="txt0",x.dataset.url=x.src=p,I.set.call(f,r),u.call(B,x),u.call(B,
f),u.call(h,B),u.call(aa,h)):(h=v.call(t,"div"),d=v.call(t,"div"),x=new ba,x.src=p,h.id=n,h.className="adt a"+q,x.className="icnm",d.className="txt1",I.set.call(d,r),u.call(h,x),P.call(B,h,f),P.call(B,d,f),q++),e++;for(;b.firstElementChild;)oa.call(b,b.firstElementChild);u.call(b,aa);b.style.display=""}function r(g){g=g.target.id?g.target:g.target.parentElement;if("menu0"==A){var b=Q(g.id.slice(1));0==b?n.call(l,p.call(m,{id:4})):1==b?(n.call(l,p.call(m,{id:0,local:1,url:"WaSQfE.html",w:770,
h:500})),L.call(a)):2==b?J(g):3==b?(n.call(l,p.call(m,{id:0,local:1,url:"WaSQfE.html",w:770,h:500})),L.call(a)):4==b?y(0,0,0):5==b?w?K("https://www.hotcleaner.com/cache-viewer.html",G.call(l,"hGGD.html")):f(d+"cache/"):6==b?J(g,"cache"):7==b?K("https://www.hotcleaner.com/clear-browsing-history.html",G.call(l,"KWrL.html")):8==b?J(g,"history"):9==b?z("https://www.hotcleaner.com/clickclean-scan-for-malware.html",d+"extensions/",1):10==b?f(d+"downloads/"):11==b?J(g,"downloads"):
12==b?K("https://www.hotcleaner.com/cookie-wiper.html",G.call(l,"aFUMzp.html")):13==b?J(g,"cookies"):14==b?w?q(115):f(d+"system/"):15==b?z("https://www.hotcleaner.com/clickclean-app.html#chvjdaa","https://myaccount.google.com/intro/privacycheckup/1",1):16==b?ca.call(R,{url:void 0,incognito:!0,focused:!0,top:-3,left:-8,width:screen.availWidth+16,height:screen.availHeight+6}):17==b?z("https://www.hotcleaner.com/security-and-privacy-software-feedback.html#chvjdaa","https://plus.google.com/101494399825495328979",
1):18==b?(n.call(l,p.call(m,{id:0,local:1,url:"WaSQfE.html",w:770,h:500})),L.call(a)):19==b?f("https://www.hotcleaner.com/clickclean-appearance.html",0):20==b?z("https://www.hotcleaner.com/clickclean_chrome_update_checker.html#chvjdaa","https://chrome.google.com/webstore/detail/clickclean/ghgabhipcejejjmhhchfonmamedcbeod/reviews",1):21==b&&F("https://chrome.google.com/webstore/detail/clickclean/ghgabhipcejejjmhhchfonmamedcbeod/reviews")}else"menu1"==A?(b=Q(g.id.slice(1)),0==b?f(d+"components/"):
1==b?f(d+"extensions/"):2==b?f(d+"flags/"):3==b?f(d+"net-internals/"):4==b?f(d+"net-internals/#dns"):5==b?K("https://www.hotcleaner.com/clear-browsing-history.html",G.call(l,"KWrL.html")):6==b?w?K("https://www.hotcleaner.com/cache-viewer.html",G.call(l,"hGGD.html")):f(d+"cache/"):7==b?ca.call(R,{url:"yEntL.html",type:"popup",focused:!0,width:350,height:216}):8==b?f("o"==d.charAt(0)?d+"about/":d+"version/"):9==b?f("https://chrome.googleblog.com/"):10==b?f(d+(w?"conflicts/":
"crashes/")):11==b?f(d+"policy/"):12==b?f("https://googlechromereleases.blogspot.com/"):13==b?f("https://www.chromium.org/developers/calendar"):14==b?f("o"==d.charAt(0)?d+"about/credits/":d+"credits/"):15==b&&f("https://code.google.com/p/chromium/issues/list")):"menu2"==A&&(b=Q(g.id.slice(1))+100,q(b))}function q(a){n.call(l,p.call(m,{id:15,v:"00"+a.toString(16)}),function(){})}function y(g,b,c){da.call(k,b?{active:!0}:{},function(e){e.forEach(function(d,h){b?pa.call(k,d.id):h?ea.call(k,d.id):qa.call(k,
d.id,{url:g?"about:blank":"chrome-search://local-ntp/local-ntp.html"});c&&h==e.length-1&&H.call(a,c,500)})})}function J(c,b,e){function g(){if(d.p28&&fa){var b=new fa("bSWDj/erased.ogg");ra.call(b)}H.call(a,function(){h.src="bSWDj/menu/done.png";H.call(a,function(){h.src=h.dataset.url;e&&da.call(k,{},function(a){a.forEach(function(a,b){ea.call(k,a.id)})})},900);C=!1},300)}if(!C){C=!0;var d,h=b?c.previousElementSibling:c.firstElementChild;h.src="bSWDj/menu/wipe.gif";n.call(l,p.call(m,{id:3}),
function(a){d=a;b?(a={id:19,v:{since:-1},v2:{}},a.v2[b]=!0,n.call(l,p.call(m,a),g)):d.p0||e?y(e,0,function(){n.call(l,p.call(m,{id:18}),g)}):n.call(l,p.call(m,{id:18}),function(){d.p25?y(0,1,g):g()})})}}function K(a,b){n.call(l,p.call(m,{id:8,v:a,v3:b}))}function f(a,b){n.call(l,p.call(m,{id:9,v:a,i:b?1:0}))}function F(a){n.call(l,p.call(m,{id:17,v:a}))}function z(a,b,c){n.call(l,p.call(m,{id:9,v:a,i:c?1:0}));n.call(l,p.call(m,{id:20,ea:"siteon-menu"}))}function D(a){return S&&ha?sa.call(N,a):ta.call(t,
a)}var E,w,C=!1,d=/Comodo/.test(ia)?"dragon://":/OPR/.test(ia)?"opera://":"chrome://",A="menu0";n.call(l,p.call(m,{id:3}),function(d){function b(a){var b=v.call(t,"div");b.className=0==a?"nav act":"nav";b.id="menu"+a;I.set.call(b,g[a]);T.call(b,"click",c,!1);return b}E=d;var g=O.call(M,"menu").split(";");d=Z.call(t);var f=v.call(t,"div"),k=v.call(t,"div"),h=v.call(t,"div");f.id="panel";k.id="menu";k.className="w102";h.id="box";701==E.ui?h.style.setProperty("filter","sepia(.5)"):702==E.ui?h.style.setProperty("filter",
"grayscale(1) brightness(1.17)"):703==E.ui?h.style.setProperty("filter","invert(1) sepia(1) saturate(0) brightness(1.7) contrast(.8)"):704==E.ui?h.style.setProperty("filter","invert(.9) sepia(1) brightness(.85) hue-rotate(20deg)"):705==E.ui?h.style.setProperty("filter","invert(.9) sepia(1) brightness(0.95) hue-rotate(155deg)"):706==E.ui&&h.style.setProperty("filter","invert(.87) sepia(1) brightness(0.95) hue-rotate(0deg)");u.call(f,k);u.call(f,h);u.call(d,f);u.call(k,b(0));u.call(k,b(1));u.call(k,
b(3));e(A,h);u.call(N,d);T.call(h,"click",r,!1);H.call(a,function(){f.className="w310"},10);/Win/.test(ua)&&n.call(l,p.call(m,{id:15,v:"000E"}),function(c){c&&c.data&&(w=c.data,k.className="w77",P.call(k,b(2),D("#menu3")),H.call(a,function(){D("#i9").firstElementChild.src="bSWDj/menu/quickscan.png";D("#i14").firstElementChild.src="bSWDj/menu/cleanup.png";var a=O.call(M,"menu0").split(";");I.set.call(D("#i9").firstElementChild.nextElementSibling,a[8]);I.set.call(D("#i14").firstElementChild.nextElementSibling,
a[12])},1))})})}var a=self.window,t=a.document,fa=a.Audio,m=a.JSON,y=a.Object,ba=a.Image,ia=navigator.appVersion||navigator.userAgent||"",ua=navigator.platform,ha=a.CustomElementRegistry?!0:!1,r=a.chrome,l=r.runtime,M=r.i18n,k=r.tabs,R=r.windows,G=l.getURL,n=l.sendMessage,ca=R.create,da=k.query,pa=k.reload,ea=k.remove,qa=k.update,O=M.getMessage,ja=Navigator.prototype,va=a.XMLHttpRequest.prototype,U=DocumentFragment.prototype,c=Document.prototype,ka=DOMImplementation.prototype,F=EventTarget.prototype,
V=Event.prototype,q=Node.prototype,e=Element.prototype,z=HTMLElement.prototype,la=HTMLMediaElement.prototype,sa=U.querySelector,v=c.createElement,Z=c.createDocumentFragment,ta=c.querySelector,T=F.addEventListener,u=q.appendChild,oa=q.removeChild,P=q.insertBefore,S=e.attachShadow||null,ra=la.play,p=m.stringify,Q=a.parseInt,L=a.close,H=a.setTimeout;try{var C=y.getOwnPropertyDescriptor(Function.prototype,"call");C&&(C.configurable=!1,C.writable=!1,y.defineProperty(Function.prototype,"call",C))}catch(Y){}var I=
y.getOwnPropertyDescriptor(q,"textContent"),ma=y.getOwnPropertyDescriptor(c,"body");try{U.querySelector=U.querySelectorAll=c.adoptNode=c.append=c.captureEvents=c.getElementById=c.getElementsByClassName=c.getElementsByName=c.getElementsByTagName=c.getElementsByTagNameNS=c.createDocumentFragment=c.createTextNode=c.createElement=c.createElementNS=c.evaluate=c.createEvent=c.createCDATASection=c.execCommand=c.querySelector=c.querySelectorAll=c.open=c.write=c.writeln=c.prepend=c.importNode=c.registerElement=
ka.createHTMLDocument=ka.createDocument=F.addEventListener=F.removeEventListener=F.dispatchEvent=V.preventDefault=V.stopPropagation=V.stopImmediatePropagation=q.appendChild=q.cloneNode=q.getRootNode=q.insertBefore=q.removeChild=q.replaceChild=e.attachShadow=e.createShadowRoot=e.getElementsByClassName=e.getElementsByTagName=e.getElementsByTagNameNS=e.append=e.remove=e.before=e.after=e.prepend=e.querySelector=e.querySelectorAll=e.requestPointerLock=e.setAttribute=e.removeAttribute=e.removeAttributeNS=
e.removeAttributeNode=e.replaceWith=e.insertAdjacentElement=e.insertAdjacentText=e.insertAdjacentHTML=z.focus=z.click=ja.sendBeacon=va.open=la.play=function(){}}catch(Y){}delete a.AnimationWorklet;delete a.Audio;delete a.AudioContext;delete a.Blob;delete a.CSS;delete a.CustomElementRegistry;delete a.CustomEvent;delete a.DOMImplementation;delete a.DOMParser;delete a.Event;delete a.FormData;delete a.Image;delete a.JSON;delete a.LayoutWorklet;delete a.MutationObserver;delete a.Navigator;delete a.PaintWorklet;
delete a.Proxy;delete a.Range;delete a.Request;delete a.Response;delete a.ServiceWorker;delete a.SharedWorker;delete a.Storage;delete a.URL;delete a.WebAssembly;delete a.WebSocket;delete a.Worker;delete a.XMLHttpRequest;delete a.XMLHttpRequestUpload;delete a.XMLSerializer;delete a.XSLTProcessor;delete a.fetch;delete a.close;delete a.open;delete a.alert;delete a.confirm;delete a.eval;delete a.localStorage;delete a.postMessage;delete a.prompt;delete a.stop;delete a.customElements;delete a.navigator;
delete q.textContent;delete c.cookie;delete c.body;delete ja.serviceWorker;delete e.innerHTML;delete e.outerHTML;delete z.innerText;delete z.outerText;delete r.Event;for(var W in r)if("runtime"==W)for(var X in r.runtime)"function"===typeof r.runtime[X]&&"connect"!==X&&(r.runtime[X]=function(){});else if("object"===typeof r[W])try{y.defineProperty(r,W,{configurable:!1,enumerable:!1,writable:!1,value:{}})}catch(Y){}var N;T.call(a,"DOMContentLoaded",function(){N=S&&ha?S.call(ma.get.call(t),{mode:"closed"}):
ma.get.call(t);var c=v.call(t,"link");c.rel="stylesheet";c.type="text/css";c.href="wQmg/xXosHf.css";u.call(N,c);H.call(a,na,1)},!0)})();
