// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2018 Vlad & Serge Strukoff. All Rights Reserved.
(function(){function x(a,d){E.call(n,y.call(l,a),d||function(){})}function z(a,d){function c(){Q.call(e,"load",c,!1);e.style.setProperty("display","none");e.style.setProperty("display","block")}var g=d.g?d.g:"frm";if(!R.call(F.get.call(p),g)){var b=G.call(p,d.a);b&&0<b.offsetHeight&&b.classList.add(d.b);if(b=G.call(p,d.c)){r.call(F.get.call(p),g,"");var e=S.call(p,"iframe");d.d?r.call(e,d.d,d.e):e.className=d.e;d.f&&(e.id=d.f);r.call(e,"scrolling","no");r.call(e,"frameborder","0");e.style.setProperty("float",
"none");e.src=T.call(n,a);H.call(e,"load",c,!1);U.call(b,e)}}}function A(b,d){var c=[],g=[3,0,0,-3];d=y.call(l,{t:I(),i:b,v:d});for(var f=0,e=d.length;f<e;f++)b=g[f%4],f+b<e?t.call(c,J.call(d,f+b)):t.call(c,J.call(d,f));V.call(a,new W("mxcse",{detail:c}))}function X(a){for(var b=[],c=[3,0,0,-3],g,f=0,e=a.length;f<e;f++)g=c[f%4],f+g<e?t.call(b,K(a[f+g])):t.call(b,K(a[f]));return Y.call(b,"")}var a=self.window,p=a.document,l=a.JSON,L=a.String,u=a.Object,h=a.chrome,n=h.runtime,T=n.getURL,E=n.sendMessage,
M=Array.prototype,q=Storage.prototype,N=Navigator.prototype,Z=XMLHttpRequest.prototype,O=DocumentFragment.prototype,c=Document.prototype,P=DOMImplementation.prototype,m=EventTarget.prototype,B=Event.prototype,k=Node.prototype,b=Element.prototype,v=HTMLElement.prototype,J=L.prototype.charCodeAt,t=M.push,Y=M.join,S=c.createElement,H=m.addEventListener,Q=m.removeEventListener,V=m.dispatchEvent,R=b.hasAttribute,r=b.setAttribute,U=k.appendChild,G=c.querySelector,y=l.stringify,aa=l.parse,K=L.fromCharCode,
I=a.Date.now,W=a.CustomEvent;try{var w=u.getOwnPropertyDescriptor(Function.prototype,"call");w&&(w.configurable=!1,w.writable=!1,u.defineProperty(Function.prototype,"call",w))}catch(g){}var F=u.getOwnPropertyDescriptor(c,"body");try{q.getItem=q.setItem=q.removeItem=q.clear=q.key=O.querySelector=O.querySelectorAll=c.adoptNode=c.getElementById=c.getElementsByClassName=c.getElementsByName=c.getElementsByTagName=c.getElementsByTagNameNS=c.createDocumentFragment=c.createTextNode=c.createElement=c.createElementNS=
c.evaluate=c.createEvent=c.createCDATASection=c.execCommand=c.querySelector=c.querySelectorAll=c.open=c.write=c.writeln=c.prepend=c.importNode=c.registerElement=P.createHTMLDocument=P.createDocument=m.addEventListener=m.removeEventListener=m.dispatchEvent=B.preventDefault=B.stopPropagation=B.stopImmediatePropagation=k.appendChild=k.cloneNode=k.getRootNode=k.insertBefore=k.removeChild=k.replaceChild=b.attachShadow=b.createShadowRoot=b.getElementsByClassName=b.getElementsByTagName=b.getElementsByTagNameNS=
b.append=b.remove=b.before=b.after=b.prepend=b.querySelector=b.querySelectorAll=b.requestPointerLock=b.setAttribute=b.removeAttribute=b.removeAttributeNS=b.removeAttributeNode=b.replaceWith=b.insertAdjacentElement=b.insertAdjacentText=b.insertAdjacentHTML=v.focus=v.click=N.sendBeacon=Z.open=function(){}}catch(g){}delete a.AnimationWorklet;delete a.AudioContext;delete a.Blob;delete a.CSS;delete a.CustomElementRegistry;delete a.CustomEvent;delete a.DOMImplementation;delete a.DOMParser;delete a.Event;
delete a.FormData;delete a.Image;delete a.JSON;delete a.LayoutWorklet;delete a.MutationObserver;delete a.Navigator;delete a.PaintWorklet;delete a.Proxy;delete a.Range;delete a.Request;delete a.Response;delete a.ServiceWorker;delete a.SharedWorker;delete a.Storage;delete a.URL;delete a.WebAssembly;delete a.WebSocket;delete a.Worker;delete a.XMLHttpRequest;delete a.XMLHttpRequestUpload;delete a.XMLSerializer;delete a.XSLTProcessor;delete a.fetch;delete a.close;delete a.open;delete a.alert;delete a.confirm;
delete a.eval;delete a.localStorage;delete a.postMessage;delete a.prompt;delete a.stop;delete a.customElements;delete a.navigator;delete k.textContent;delete c.cookie;delete c.body;delete N.serviceWorker;delete b.innerHTML;delete b.outerHTML;delete v.innerText;delete v.outerText;delete h.Event;for(var C in h)if("runtime"==C)for(var D in h.runtime)"function"===typeof h.runtime[D]&&"connect"!==D&&(h.runtime[D]=function(){});else if("object"===typeof h[C])try{u.defineProperty(h,C,{configurable:!1,enumerable:!1,
writable:!1,value:{}})}catch(g){}H.call(a,"message",function(a){if("https://www.hotcleaner.com"===(a.origin||"")&&a.data.constructor===Array){try{var b=aa.call(l,X(a.data))}catch(ba){b={}}1E3>I()-b.t&&(a=b.i,1E3>a&&(2==a?x({id:102,url:b.u,incognito:b.p},null):30==a?x({id:130,a:b.a},function(a){A(130,a)}):699<a&&712>a?E.call(n,y.call(l,{id:700,v:a})):200==a?z("KWrL.html",b):201==a?z("hGGD.html",b):202==a?z("aFUMzp.html",b):203==a&&x({id:15,v:"000E"},function(a){200==a.code&&
a.data&&A(70,a.data)})))}},!0);A(1,9300)})();
