// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2018 Vlad & Serge Strukoff. All Rights Reserved.
(function(){function G(){function a(b,c){for(var d,k,e,f=0,h=c.length;f<h;f++)if(d=c[f],1==d.t){k=d.n?H.call(l,"http://www.w3.org/2000/svg",d.l):I.call(l,d.l);for(var g=0,m=d.a&&d.a.length||0;g<m;g++)e=d.a[g],J.call(k,e.n,e.v);d.c&&a(k,d.c);t.call(b,k)}else 3==d.t&&t.call(b,K.call(l,d.v))}var b=L.call(h,'[{"t":1,"l":"link","a":[{"n":"rel","v":"stylesheet"},{"n":"type","v":"text/css"},{"n":"href","v":"wQmg/MJKFPud.css"}]},{"t":1,"l":"div","a":[{"n":"class","v":"host"}],"c":[{"t":1,"l":"h1","c":[{"t":3,"v":"Thank You for using Click&Clean"}]},{"t":1,"l":"h3","c":[{"t":3,"v":"Software Made to Make Your Life Better!"}]},{"t":1,"l":"button","a":[{"n":"class","v":"b0"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"bSWDj/opt-home64.webp"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Home"}]}]},{"t":1,"l":"button","a":[{"n":"class","v":"b1"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"bSWDj/opt-opt64.webp"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Options"}]}]},{"t":1,"l":"button","a":[{"n":"class","v":"b2"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"bSWDj/opt-rate64.webp"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Rate"}]}]},{"t":1,"l":"button","a":[{"n":"class","v":"b3"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"bSWDj/opt-contact64.webp"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Support"}]}]},{"t":1,"l":"br"}]}]');
p=u&&A?u.call(B.get.call(l),{mode:"closed"}):B.get.call(l);var c=M.call(l);a(c,b);t.call(p,c)}function N(){O.call(P(".b0"));C.call(p,"click",function(a){var b=a.target;if(b=b.className||b.parentElement&&b.parentElement.className||"")"b0"===b||"b3"===b?"b0"===b?D("https://www.hotcleaner.com/clickclean_chrome.html#chvjdaa",1):"b3"===b&&D("https://www.hotcleaner.com/security-and-privacy-software-feedback.html#ehveihf",1):"b1"===b?v.call(g,w.call(h,{id:0,local:1,url:"WaSQfE.html",w:770,h:500})):
"b2"===b&&v.call(g,w.call(h,{id:17,v:"https://chrome.google.com/webstore/detail/clickclean/ghgabhipcejejjmhhchfonmamedcbeod/reviews"})),Q.call(a),R.call(a)},!0)}function D(a,b){v.call(g,w.call(h,{id:9,v:a,i:b?1:0}))}function P(a){return u&&A?S.call(p,a):T.call(l,a)}var a=self.window,l=a.document,h=a.JSON,A=a.CustomElementRegistry?!0:!1,e=a.chrome,g=e.runtime,v=g.sendMessage,U=g.getURL,E=Navigator.prototype,V=a.XMLHttpRequest.prototype,x=DocumentFragment.prototype,b=Document.prototype,F=DOMImplementation.prototype,
q=EventTarget.prototype,m=Event.prototype,f=Node.prototype,c=Element.prototype,n=HTMLElement.prototype,I=b.createElement,H=b.createElementNS,C=q.addEventListener,M=b.createDocumentFragment,J=c.setAttribute,S=x.querySelector,T=b.querySelector,O=n.focus,t=f.appendChild,K=b.createTextNode,Q=m.preventDefault,R=m.stopPropagation,u=c.attachShadow||null,w=h.stringify,L=h.parse;try{var r=Object.getOwnPropertyDescriptor(Function.prototype,"call");r&&(r.configurable=!1,r.writable=!1,Object.defineProperty(Function.prototype,
"call",r))}catch(k){}var B=Object.getOwnPropertyDescriptor(b,"body");try{x.querySelector=x.querySelectorAll=b.adoptNode=b.append=b.captureEvents=b.getElementById=b.getElementsByClassName=b.getElementsByName=b.getElementsByTagName=b.getElementsByTagNameNS=b.createDocumentFragment=b.createTextNode=b.createElement=b.createElementNS=b.evaluate=b.createEvent=b.createCDATASection=b.execCommand=b.querySelector=b.querySelectorAll=b.open=b.write=b.writeln=b.prepend=b.importNode=b.registerElement=F.createHTMLDocument=
F.createDocument=q.addEventListener=q.removeEventListener=q.dispatchEvent=m.preventDefault=m.stopPropagation=m.stopImmediatePropagation=f.appendChild=f.cloneNode=f.getRootNode=f.insertBefore=f.removeChild=f.replaceChild=c.attachShadow=c.createShadowRoot=c.getElementsByClassName=c.getElementsByTagName=c.getElementsByTagNameNS=c.append=c.remove=c.before=c.after=c.prepend=c.querySelector=c.querySelectorAll=c.requestPointerLock=c.setAttribute=c.removeAttribute=c.removeAttributeNS=c.removeAttributeNode=
c.replaceWith=c.insertAdjacentElement=c.insertAdjacentText=c.insertAdjacentHTML=n.focus=n.click=E.sendBeacon=V.open=function(){}}catch(k){}delete a.AnimationWorklet;delete a.Audio;delete a.AudioContext;delete a.Blob;delete a.CSS;delete a.CustomElementRegistry;delete a.CustomEvent;delete a.DOMImplementation;delete a.DOMParser;delete a.Event;delete a.FormData;delete a.Image;delete a.JSON;delete a.LayoutWorklet;delete a.MutationObserver;delete a.Navigator;delete a.PaintWorklet;delete a.Proxy;delete a.Range;
delete a.Request;delete a.Response;delete a.ServiceWorker;delete a.SharedWorker;delete a.Storage;delete a.URL;delete a.WebAssembly;delete a.WebSocket;delete a.Worker;delete a.XMLHttpRequest;delete a.XMLHttpRequestUpload;delete a.XMLSerializer;delete a.XSLTProcessor;delete a.fetch;delete a.close;delete a.open;delete a.alert;delete a.confirm;delete a.eval;delete a.localStorage;delete a.postMessage;delete a.prompt;delete a.stop;delete a.customElements;delete a.navigator;delete f.textContent;delete b.cookie;
delete b.body;delete E.serviceWorker;delete c.innerHTML;delete c.outerHTML;delete n.innerText;delete n.outerText;delete e.Event;for(var y in e)if("runtime"==y)for(var z in e.runtime)"function"===typeof e.runtime[z]&&"connect"!==z&&(e.runtime[z]=function(){});else if("object"===typeof e[y])try{Object.defineProperty(e,y,{configurable:!1,enumerable:!1,writable:!1,value:{}})}catch(k){}U.call(g,"mDwj.html");var p;C.call(a,"DOMContentLoaded",function(){G();N()},!0)})();
